---
- name: pull image, create yaml file and deploy tomcat to k8s
  hosts: local
  tasks:
    - name: pull image from dockerhub
      shell: docker pull thanhvu638/javaweb:{{ version }}
    
    - name: create app.yaml
      template:
        src: ./app.yaml.j2
        dest: /var/lib/jenkins/workspace/java-tomcat/app.yaml
      vars:
        version: "{{ version }}"
      
    - name: delete old version tomcat deployment
      command: echo "123" | sudo /usr/local/bin/kubectl delete deployment tomcat-deployment --kubeconfig /home/thanhnga/.kube/config
    
    - name: run new version of tomcat deployment
      command: echo "123" | sudo /usr/local/bin/kubectl apply -f /var/lib/jenkins/workspace/java-tomcat/app.yaml --kubeconfig /home/thanhnga/.kube/config
      register: kubectl_output

    - name: Display the stdout of kubectl get pods
      debug:
        var: kubectl_output.stdout

    - name: Display the stderr of kubectl get pods
      debug:
        var: kubectl_output.stderr

    - name: Display the return code of kubectl get pods
      debug:
        var: kubectl_output.rc

    - name: Display the stdout lines of kubectl get pods
      debug:
        var: kubectl_output.stdout_lines

    - name: Display the stderr lines of kubectl get pods
      debug:
        var: kubectl_output.stderr_lines
