---
- name: Build docker image, deploy k8s and push image to docker hub
  hosts: local
  tasks:
    - name: Update new version of image
      command: python3 /var/lib/jenkins/workspace/java-tomcat/update_version.py
    
    - name: Update new version in source code
      sudo: yes
      sudo_user: thanhnga
      shell: cp /var/lib/jenkins/workspace/java-tomcat/version.txt /home/thanhnga/Documents/learn/ansible/project/javaweb/version.txt

    - name: Build docker image
      command: python3 /var/lib/jenkins/workspace/java-tomcat/build_image.py

    - name: Push image to dockerhub
      command: python3 /var/lib/jenkins/workspace/java-tomcat/push_image.py
    
    - name: Deploy to k8s
      command: python3 /var/lib/jenkins/workspace/java-tomcat/deploy.py