---
- name: pull image, create yaml file and deploy tomcat to k8s
  hosts: local
  tasks:
    - name: pull image from dockerhub
      shell: docker pull thanhvu638/javaweb:{{ version }}
    
    - name: create app.yaml
      template:
        src: ./app.yaml.j2
        dest: /var/lib/jenkins/workspace/java-tomcat/app.yaml
      vars:
        version: "{{ version }}"
      
    - name: deploy application to k8s
      command: kubectl get pod
      become: no
