---
- name: Build docker image, deploy k8s and push image to docker hub
  hosts: local
  tasks:
    - name: Update new version of image
      command: python3 /var/lib/jenkins/workspace/java-tomcat/update_version.py

    - name: Build docker image
      command: python3 /var/lib/jenkins/workspace/java-tomcat/build_image.py

    - name: Push image to dockerhub
      command: python3 /var/lib/jenkins/workspace/java-tomcat/push_image.py
    

