apiVersion: apps/v1
kind: Deployment
metadata:
  name: tomcat-deployment
  labels: 
    app: tomcat-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tomcat-app
  template:
    metadata:
      labels:
        app: tomcat-app
    spec:
      containers:
        - name: tomcat-app
          image: thanhvu638/javaweb:v3
          ports: 
          - containerPort: 8080

--- 

apiVersion: v1 
kind: Service
metadata:
  name: tomcat-service
spec:
  selector:
    app: tomcat-app
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30002
    
